
export type Locale = 'ar' | 'en' | 'fr' | 'tr' | 'id';

export const translations = {
  ar: {
    nav: {
      habits: 'العادة',
      adhkar: 'الأذكار',
      summaries: 'ملخصات',
    },
    home: {
      addHabit: 'إضافة عادة جديدة',
      habitName: 'اسم العادة',
      habitNamePlaceholder: 'مثال: قضم الأظافر',
      habitDescription: 'وصف العادة (اختياري)',
      habitDescriptionPlaceholder: 'صف العادة التي تريد التخلص منها',
      reminderMessage: 'رسالة التذكير',
      reminderMessagePlaceholder: 'رسالة تظهر مع الإشعار لتذكيرك',
      reminderFrequency: 'تكرار التذكير',
      every: 'كل',
      intervalUnit: 'اختر وحدة',
      seconds: 'ثوانٍ',
      minutes: 'دقائق',
      hours: 'ساعات',
      days: 'أيام',
      reminderType: 'نوع التذكير',
      notification: 'إشعار نصي',
      audio: 'تنبيه صوتي',
      recordAudio: 'تسجيل صوتي مخصص',
      record: 'تسجيل',
      stop: 'إيقاف',
      deleteAudio: 'حذف التسجيل',
      addHabitButton: 'إضافة العادة',
      yourHabits: 'قائمة عاداتك',
      emptyHabitsTitle: 'القائمة فارغة',
      emptyHabitsDescription: 'لم تقم بإضافة أي عادات بعد. ابدأ بإضافة واحدة!',
      deleteConfirmTitle: 'هل أنت متأكد؟',
      deleteConfirmDescription: 'سيتم حذف هذه العادة بشكل دائم. لا يمكن التراجع عن هذا الإجراء وسيتم إيقاف جميع الإشعارات المتعلقة بها.',
      cancel: 'إلغاء',
      delete: 'حذف',
      habitAddedSuccess: 'تم إضافة العادة بنجاح!',
      habitAddedDescription: (name: string) => `سيتم تذكيرك بشأن "${name}".`,
      habitDeletedSuccess: 'تم حذف العادة',
      habitDeletedDescription: 'تم إيقاف جميع التذكيرات لهذه العادة.',
      micError: 'خطأ في الوصول إلى الميكروفون',
      micErrorDescription: 'يرجى التأكد من منح الإذن لاستخدام الميكروفون.',
      audioRecordingRequired: 'يرجى تسجيل تنبيه صوتي أولاً.',
      getFrequencyText: (interval: number, unit: string) => `كل ${interval} ${
        {
          seconds: 'ثوانٍ',
          minutes: 'دقائق',
          hours: 'ساعات',
          days: 'أيام',
        }[unit] || unit
      }`
    },
    header: {
      toggleLanguage: 'تغيير اللغة',
      arabic: 'العربية',
      english: 'English',
      french: 'Français',
      turkish: 'Türkçe',
      indonesian: 'Bahasa Indonesia',
      langChangedTitle: 'تم تغيير اللغة',
      langChangedTo: (lang: string) => `تم التبديل إلى ${lang}.`,
      toggleNotifications: 'تفعيل/إلغاء تفعيل الإشعارات',
      notificationsOn: 'تم تفعيل الإشعارات',
      notificationsOnDescription: 'ستتلقى تذكيرات لعاداتك.',
      notificationsOff: 'تم إيقاف الإشعارات',
      notificationsOffDescription: 'لن تتلقى أي تذكيرات.',
      toggleTheme: 'تغيير الثيم',
    },
    adhkar: {
      morning: 'أذكار الصباح',
      evening: 'أذكار المساء',
    },
    summaries: {
      title: 'ملخصات كتب',
      description: 'مجموعة من الملخصات العميقة لكتب غيرت حياة الملايين في مجال تطوير الذات والعادات.',
      author: 'المؤلف',
    }
  },
  en: {
    nav: {
      habits: 'Habit',
      adhkar: 'Adhkar',
      summaries: 'Summaries',
    },
    home: {
      addHabit: 'Add New Habit',
      habitName: 'Habit Name',
      habitNamePlaceholder: 'e.g., Nail Biting',
      habitDescription: 'Habit Description (optional)',
      habitDescriptionPlaceholder: 'Describe the habit you want to quit',
      reminderMessage: 'Reminder Message',
      reminderMessagePlaceholder: 'A message to show with the notification',
      reminderFrequency: 'Reminder Frequency',
      every: 'Every',
      intervalUnit: 'Select unit',
      seconds: 'seconds',
      minutes: 'minutes',
      hours: 'hours',
      days: 'days',
      reminderType: 'Reminder Type',
      notification: 'Text Notification',
      audio: 'Audio Alert',
      recordAudio: 'Custom Audio Recording',
      record: 'Record',
      stop: 'Stop',
      deleteAudio: 'Delete Recording',
      addHabitButton: 'Add Habit',
      yourHabits: 'Your Habits List',
      emptyHabitsTitle: 'List is empty',
      emptyHabitsDescription: 'You haven\'t added any habits yet. Start by adding one!',
      deleteConfirmTitle: 'Are you sure?',
      deleteConfirmDescription: 'This action cannot be undone. This will permanently delete the habit and stop all its notifications.',
      cancel: 'Cancel',
      delete: 'Delete',
      habitAddedSuccess: 'Habit added successfully!',
      habitAddedDescription: (name: string) => `You will be reminded about "${name}".`,
      habitDeletedSuccess: 'Habit Deleted',
      habitDeletedDescription: 'All reminders for this habit have been stopped.',
      micError: 'Microphone Access Error',
      micErrorDescription: 'Please ensure you have granted permission to use the microphone.',
      audioRecordingRequired: 'Please record an audio alert first.',
      getFrequencyText: (interval: number, unit: string) => `Every ${interval} ${
        {
          seconds: interval === 1 ? 'second' : 'seconds',
          minutes: interval === 1 ? 'minute' : 'minutes',
          hours: interval === 1 ? 'hour' : 'hours',
          days: interval === 1 ? 'day' : 'days',
        }[unit] || unit
      }`
    },
    header: {
      toggleLanguage: 'Change Language',
      arabic: 'العربية',
      english: 'English',
      french: 'Français',
      turkish: 'Türkçe',
      indonesian: 'Bahasa Indonesia',
      langChangedTitle: 'Language Changed',
      langChangedTo: (lang: string) => `Switched to ${lang}.`,
      toggleNotifications: 'Toggle notifications',
      notificationsOn: 'Notifications Enabled',
      notificationsOnDescription: 'You will receive reminders for your habits.',
      notificationsOff: 'Notifications Disabled',
      notificationsOffDescription: 'You will not receive any reminders.',
      toggleTheme: 'Toggle Theme',
    },
    adhkar: {
      morning: 'Morning Adhkar',
      evening: 'Evening Adhkar',
    },
    summaries: {
      title: 'Book Summaries',
      description: 'A collection of in-depth summaries of books that have changed the lives of millions in self-development and habits.',
      author: 'Author',
    }
  },
  fr: {
    nav: {
      habits: 'Habitude',
      adhkar: 'Adhkar',
      summaries: 'Résumés',
    },
    home: {
      addHabit: 'Ajouter une habitude',
      habitName: 'Nom de l\'habitude',
      habitNamePlaceholder: 'Ex: Se ronger les ongles',
      habitDescription: 'Description (optionnel)',
      habitDescriptionPlaceholder: 'Décrivez l\'habitude que vous voulez arrêter',
      reminderMessage: 'Message de rappel',
      reminderMessagePlaceholder: 'Un message à afficher avec la notification',
      reminderFrequency: 'Fréquence du rappel',
      every: 'Chaque',
      intervalUnit: 'Unité',
      seconds: 'secondes',
      minutes: 'minutes',
      hours: 'heures',
      days: 'jours',
      reminderType: 'Type de rappel',
      notification: 'Notification texte',
      audio: 'Alerte audio',
      recordAudio: 'Enregistrement audio',
      record: 'Enregistrer',
      stop: 'Arrêter',
      deleteAudio: 'Supprimer',
      addHabitButton: 'Ajouter l\'habitude',
      yourHabits: 'Vos habitudes',
      emptyHabitsTitle: 'La liste est vide',
      emptyHabitsDescription: 'Commencez par ajouter une nouvelle habitude!',
      deleteConfirmTitle: 'Êtes-vous sûr?',
      deleteConfirmDescription: 'Cette action est irréversible et supprimera définitivement l\'habitude.',
      cancel: 'Annuler',
      delete: 'Supprimer',
      habitAddedSuccess: 'Habitude ajoutée!',
      habitAddedDescription: (name: string) => `Vous recevrez des rappels pour "${name}".`,
      habitDeletedSuccess: 'Habitude supprimée',
      habitDeletedDescription: 'Les rappels pour cette habitude ont été arrêtés.',
      micError: 'Erreur microphone',
      micErrorDescription: 'Veuillez autoriser l\'accès au microphone.',
      audioRecordingRequired: 'Veuillez d\'abord enregistrer une alerte audio.',
      getFrequencyText: (interval: number, unit: string) => `Toutes les ${interval} ${
        {
          seconds: interval === 1 ? 'seconde' : 'secondes',
          minutes: interval === 1 ? 'minute' : 'minutes',
          hours: interval === 1 ? 'heure' : 'heures',
          days: interval === 1 ? 'jour' : 'jours',
        }[unit] || unit
      }`
    },
    header: {
      toggleLanguage: 'Changer de langue',
      arabic: 'العربية',
      english: 'English',
      french: 'Français',
      turkish: 'Türkçe',
      indonesian: 'Bahasa Indonesia',
      langChangedTitle: 'Langue modifiée',
      langChangedTo: (lang: string) => `Passage à ${lang}.`,
      toggleNotifications: 'Activer/désactiver les notifications',
      notificationsOn: 'Notifications activées',
      notificationsOnDescription: 'Vous recevrez des rappels.',
      notificationsOff: 'Notifications désactivées',
      notificationsOffDescription: 'Vous ne recevrez aucun rappel.',
      toggleTheme: 'Changer de thème',
    },
    adhkar: {
      morning: 'Adhkar du Matin',
      evening: 'Adhkar du Soir',
    },
    summaries: {
      title: 'Résumés de livres',
      description: 'Une collection de résumés de livres sur le développement personnel et les habitudes.',
      author: 'Auteur',
    }
  },
  tr: {
    nav: {
      habits: 'Alışkanlık',
      adhkar: 'Zikirler',
      summaries: 'Özetler',
    },
    home: {
      addHabit: 'Yeni Alışkanlık Ekle',
      habitName: 'Alışkanlık Adı',
      habitNamePlaceholder: 'Örn: Tırnak yemek',
      habitDescription: 'Açıklama (isteğe bağlı)',
      habitDescriptionPlaceholder: 'Bırakmak istediğiniz alışkanlığı tanımlayın',
      reminderMessage: 'Hatırlatma Mesajı',
      reminderMessagePlaceholder: 'Bildirimle gösterilecek bir mesaj',
      reminderFrequency: 'Hatırlatma Sıklığı',
      every: 'Her',
      intervalUnit: 'Birim seç',
      seconds: 'saniye',
      minutes: 'dakika',
      hours: 'saat',
      days: 'gün',
      reminderType: 'Hatırlatma Türü',
      notification: 'Metin Bildirimi',
      audio: 'Sesli Uyarı',
      recordAudio: 'Özel Ses Kaydı',
      record: 'Kaydet',
      stop: 'Durdur',
      deleteAudio: 'Kaydı Sil',
      addHabitButton: 'Alışkanlığı Ekle',
      yourHabits: 'Alışkanlık Listeniz',
      emptyHabitsTitle: 'Liste boş',
      emptyHabitsDescription: 'Henüz bir alışkanlık eklemediniz. Bir tane ekleyerek başlayın!',
      deleteConfirmTitle: 'Emin misiniz?',
      deleteConfirmDescription: 'Bu işlem geri alınamaz. Alışkanlığı kalıcı olarak silecek ve tüm bildirimlerini durduracaktır.',
      cancel: 'İptal',
      delete: 'Sil',
      habitAddedSuccess: 'Alışkanlık başarıyla eklendi!',
      habitAddedDescription: (name: string) => `"${name}" için hatırlatıcılar alacaksınız.`,
      habitDeletedSuccess: 'Alışkanlık Silindi',
      habitDeletedDescription: 'Bu alışkanlık için tüm hatırlatıcılar durduruldu.',
      micError: 'Mikrofon Erişim Hatası',
      micErrorDescription: 'Lütfen mikrofon kullanım izni verdiğinizden emin olun.',
      audioRecordingRequired: 'Lütfen önce bir sesli uyarı kaydedin.',
      getFrequencyText: (interval: number, unit: string) => `Her ${interval} ${
        {
          seconds: 'saniyede bir',
          minutes: 'dakikada bir',
          hours: 'saatte bir',
          days: 'günde bir',
        }[unit] || unit
      }`
    },
    header: {
      toggleLanguage: 'Dili Değiştir',
      arabic: 'العربية',
      english: 'English',
      french: 'Français',
      turkish: 'Türkçe',
      indonesian: 'Bahasa Indonesia',
      langChangedTitle: 'Dil Değiştirildi',
      langChangedTo: (lang: string) => `${lang} diline geçildi.`,
      toggleNotifications: 'Bildirimleri aç/kapat',
      notificationsOn: 'Bildirimler Etkinleştirildi',
      notificationsOnDescription: 'Alışkanlıklarınız için hatırlatıcılar alacaksınız.',
      notificationsOff: 'Bildirimler Devre Dışı Bırakıldı',
      notificationsOffDescription: 'Herhangi bir hatırlatma almayacaksınız.',
      toggleTheme: 'Temayı Değiştir',
    },
    adhkar: {
      morning: 'Sabah Zikirleri',
      evening: 'Akşam Zikirleri',
    },
    summaries: {
      title: 'Kitap Özetleri',
      description: 'Kişisel gelişim ve alışkanlıklar alanında milyonlarca insanın hayatını değiştiren kitapların derinlemesine özetlerinden oluşan bir koleksiyon.',
      author: 'Yazar',
    }
  },
  id: {
    nav: {
      habits: 'Kebiasaan',
      adhkar: 'Dzikir',
      summaries: 'Ringkasan',
    },
    home: {
      addHabit: 'Tambah Kebiasaan Baru',
      habitName: 'Nama Kebiasaan',
      habitNamePlaceholder: 'Contoh: Menggigit kuku',
      habitDescription: 'Deskripsi (opsional)',
      habitDescriptionPlaceholder: 'Jelaskan kebiasaan yang ingin Anda hentikan',
      reminderMessage: 'Pesan Pengingat',
      reminderMessagePlaceholder: 'Pesan untuk ditampilkan dengan notifikasi',
      reminderFrequency: 'Frekuensi Pengingat',
      every: 'Setiap',
      intervalUnit: 'Pilih satuan',
      seconds: 'detik',
      minutes: 'menit',
      hours: 'jam',
      days: 'hari',
      reminderType: 'Jenis Pengingat',
      notification: 'Notifikasi Teks',
      audio: 'Peringatan Audio',
      recordAudio: 'Rekaman Audio Kustom',
      record: 'Rekam',
      stop: 'Berhenti',
      deleteAudio: 'Hapus Rekaman',
      addHabitButton: 'Tambah Kebiasaan',
      yourHabits: 'Daftar Kebiasaan Anda',
      emptyHabitsTitle: 'Daftar kosong',
      emptyHabitsDescription: 'Anda belum menambahkan kebiasaan apa pun. Mulailah dengan menambahkan satu!',
      deleteConfirmTitle: 'Apakah Anda yakin?',
      deleteConfirmDescription: 'Tindakan ini tidak dapat dibatalkan. Ini akan menghapus kebiasaan secara permanen dan menghentikan semua notifikasinya.',
      cancel: 'Batal',
      delete: 'Hapus',
      habitAddedSuccess: 'Kebiasaan berhasil ditambahkan!',
      habitAddedDescription: (name: string) => `Anda akan diingatkan tentang "${name}".`,
      habitDeletedSuccess: 'Kebiasaan Dihapus',
      habitDeletedDescription: 'Semua pengingat untuk kebiasaan ini telah dihentikan.',
      micError: 'Kesalahan Akses Mikrofon',
      micErrorDescription: 'Harap pastikan Anda telah memberikan izin untuk menggunakan mikrofon.',
      audioRecordingRequired: 'Harap rekam peringatan audio terlebih dahulu.',
      getFrequencyText: (interval: number, unit: string) => `Setiap ${interval} ${
        {
          seconds: interval === 1 ? 'detik' : 'detik',
          minutes: interval === 1 ? 'menit' : 'menit',
          hours: interval === 1 ? 'jam' : 'jam',
          days: interval === 1 ? 'hari' : 'hari',
        }[unit] || unit
      }`
    },
    header: {
      toggleLanguage: 'Ubah Bahasa',
      arabic: 'العربية',
      english: 'English',
      french: 'Français',
      turkish: 'Türkçe',
      indonesian: 'Bahasa Indonesia',
      langChangedTitle: 'Bahasa Diubah',
      langChangedTo: (lang: string) => `Beralih ke ${lang}.`,
      toggleNotifications: 'Aktifkan/nonaktifkan notifikasi',
      notificationsOn: 'Notifikasi Diaktifkan',
      notificationsOnDescription: 'Anda akan menerima pengingat untuk kebiasaan Anda.',
      notificationsOff: 'Notifikasi Dinonaktifkan',
      notificationsOffDescription: 'Anda tidak akan menerima pengingat apa pun.',
      toggleTheme: 'Ubah Tema',
    },
    adhkar: {
      morning: 'Dzikir Pagi',
      evening: 'Dzikir Petang',
    },
    summaries: {
      title: 'Ringkasan Buku',
      description: 'Kumpulan ringkasan mendalam dari buku-buku yang telah mengubah kehidupan jutaan orang dalam pengembangan diri dan kebiasaan.',
      author: 'Penulis',
    }
  },
};
