
export type Locale = 'ar' | 'en';

export const translations = {
  ar: {
    nav: {
      habits: 'العادة',
      adhkar: 'الأذكار',
      summaries: 'ملخصات',
    },
    home: {
      addHabit: 'إضافة عادة جديدة',
      habitName: 'اسم العادة',
      habitNamePlaceholder: 'مثال: قضم الأظافر',
      habitDescription: 'وصف العادة (اختياري)',
      habitDescriptionPlaceholder: 'صف العادة التي تريد التخلص منها',
      reminderMessage: 'رسالة التذكير',
      reminderMessagePlaceholder: 'رسالة تظهر مع الإشعار لتذكيرك',
      reminderFrequency: 'تكرار التذكير',
      every: 'كل',
      intervalUnit: 'اختر وحدة',
      seconds: 'ثوانٍ',
      minutes: 'دقائق',
      hours: 'ساعات',
      days: 'أيام',
      reminderType: 'نوع التذكير',
      notification: 'إشعار نصي',
      audio: 'تنبيه صوتي',
      recordAudio: 'تسجيل صوتي مخصص',
      record: 'تسجيل',
      stop: 'إيقاف',
      deleteAudio: 'حذف التسجيل',
      addHabitButton: 'إضافة العادة',
      yourHabits: 'قائمة عاداتك',
      emptyHabitsTitle: 'القائمة فارغة',
      emptyHabitsDescription: 'لم تقم بإضافة أي عادات بعد. ابدأ بإضافة واحدة!',
      deleteConfirmTitle: 'هل أنت متأكد؟',
      deleteConfirmDescription: 'سيتم حذف هذه العادة بشكل دائم. لا يمكن التراجع عن هذا الإجراء وسيتم إيقاف جميع الإشعارات المتعلقة بها.',
      cancel: 'إلغاء',
      delete: 'حذف',
      habitAddedSuccess: 'تم إضافة العادة بنجاح!',
      habitAddedDescription: (name: string) => `سيتم تذكيرك بشأن "${name}".`,
      habitDeletedSuccess: 'تم حذف العادة',
      habitDeletedDescription: 'تم إيقاف جميع التذكيرات لهذه العادة.',
      micError: 'خطأ في الوصول إلى الميكروفون',
      micErrorDescription: 'يرجى التأكد من منح الإذن لاستخدام الميكروفون.',
      audioRecordingRequired: 'يرجى تسجيل تنبيه صوتي أولاً.',
      getFrequencyText: (interval: number, unit: string) => `كل ${interval} ${
        {
          seconds: 'ثوانٍ',
          minutes: 'دقائق',
          hours: 'ساعات',
          days: 'أيام',
        }[unit] || unit
      }`
    },
    header: {
      toggleLanguage: 'تغيير اللغة',
      arabic: 'العربية',
      english: 'English',
      langChangedTitle: 'تم تغيير اللغة',
      langChangedToArabic: 'تم التبديل إلى اللغة العربية.',
      langChangedToEnglish: 'Switched to English.',
      toggleNotifications: 'تفعيل/إلغاء تفعيل الإشعارات',
      notificationsOn: 'تم تفعيل الإشعارات',
      notificationsOnDescription: 'ستتلقى تذكيرات لعاداتك.',
      notificationsOff: 'تم إيقاف الإشعارات',
      notificationsOffDescription: 'لن تتلقى أي تذكيرات.',
      toggleTheme: 'تغيير الثيم',
    },
    adhkar: {
      morning: 'أذكار الصباح',
      evening: 'أذكار المساء',
    }
  },
  en: {
    nav: {
      habits: 'Habit',
      adhkar: 'Adhkar',
      summaries: 'Summaries',
    },
    home: {
      addHabit: 'Add New Habit',
      habitName: 'Habit Name',
      habitNamePlaceholder: 'e.g., Nail Biting',
      habitDescription: 'Habit Description (optional)',
      habitDescriptionPlaceholder: 'Describe the habit you want to quit',
      reminderMessage: 'Reminder Message',
      reminderMessagePlaceholder: 'A message to show with the notification',
      reminderFrequency: 'Reminder Frequency',
      every: 'Every',
      intervalUnit: 'Select unit',
      seconds: 'seconds',
      minutes: 'minutes',
      hours: 'hours',
      days: 'days',
      reminderType: 'Reminder Type',
      notification: 'Text Notification',
      audio: 'Audio Alert',
      recordAudio: 'Custom Audio Recording',
      record: 'Record',
      stop: 'Stop',
      deleteAudio: 'Delete Recording',
      addHabitButton: 'Add Habit',
      yourHabits: 'Your Habits List',
      emptyHabitsTitle: 'List is empty',
      emptyHabitsDescription: 'You haven\'t added any habits yet. Start by adding one!',
      deleteConfirmTitle: 'Are you sure?',
      deleteConfirmDescription: 'This action cannot be undone. This will permanently delete the habit and stop all its notifications.',
      cancel: 'Cancel',
      delete: 'Delete',
      habitAddedSuccess: 'Habit added successfully!',
      habitAddedDescription: (name: string) => `You will be reminded about "${name}".`,
      habitDeletedSuccess: 'Habit Deleted',
      habitDeletedDescription: 'All reminders for this habit have been stopped.',
      micError: 'Microphone Access Error',
      micErrorDescription: 'Please ensure you have granted permission to use the microphone.',
      audioRecordingRequired: 'Please record an audio alert first.',
      getFrequencyText: (interval: number, unit: string) => `Every ${interval} ${
        {
          seconds: interval === 1 ? 'second' : 'seconds',
          minutes: interval === 1 ? 'minute' : 'minutes',
          hours: interval === 1 ? 'hour' : 'hours',
          days: interval === 1 ? 'day' : 'days',
        }[unit] || unit
      }`
    },
    header: {
      toggleLanguage: 'Change Language',
      arabic: 'العربية',
      english: 'English',
      langChangedTitle: 'Language Changed',
      langChangedToArabic: 'تم التبديل إلى اللغة العربية.',
      langChangedToEnglish: 'Switched to English.',
      toggleNotifications: 'Toggle notifications',
      notificationsOn: 'Notifications Enabled',
      notificationsOnDescription: 'You will receive reminders for your habits.',
      notificationsOff: 'Notifications Disabled',
      notificationsOffDescription: 'You will not receive any reminders.',
      toggleTheme: 'Toggle Theme',
    },
    adhkar: {
      morning: 'Morning Adhkar',
      evening: 'Evening Adhkar',
    }
  },
};
