

export const motivationalQuotes: { [key: string]: { quote: string; author: string }[] } = {
    ar: [
        { quote: "إن أعظم مجد ليس في عدم السقوط أبدًا، بل في النهوض في كل مرة نسقط فيها.", author: "نيلسون مانديلا" },
        { quote: "الطريقة الوحيدة للقيام بعمل عظيم هي أن تحب ما تفعله.", author: "ستيف جوبز" },
        { quote: "كن أنت التغيير الذي تريد أن تراه في العالم.", author: "غاندي" },
        { quote: "النجاح ليس نهائيًا، والفشل ليس قاتلًا: إنها الشجاعة لمواصلة ما يهم.", author: "ونستون تشرشل" },
        { quote: "لا تنتظر الفرصة، بل اصنعها.", author: "جورج برنارد شو" },
        { quote: "العقل هو كل شيء. ما تفكر فيه، تصبح عليه.", author: "بوذا" },
        { quote: "ابدأ من حيث أنت. استخدم ما لديك. افعل ما تستطيع.", author: "آرثر آش" },
        { quote: "التحديات هي ما تجعل الحياة مثيرة للاهتمام، والتغلب عليها هو ما يجعل الحياة ذات معنى.", author: "جوشوا ج. مارين" },
        { quote: "الشخص الذي لم يرتكب أي خطأ لم يجرب أي شيء جديد.", author: "ألبرت أينشتاين" },
        { quote: "أفضل وقت لزرع شجرة كان قبل 20 عامًا. ثاني أفضل وقت هو الآن.", author: "مثل صيني" },
        { quote: "الفشل هو مجرد فرصة للبدء من جديد، ولكن هذه المرة بذكاء أكبر.", author: "هنري فورد" },
        { quote: "لا تخف من التخلي عن الجيد للحصول على الأفضل.", author: "جون د. روكفلر" },
        { quote: "إذا كنت تريد أن ترفع نفسك، فارفع شخصًا آخر.", author: "بوكر تي واشنطن" },
        { quote: "أنا لم أفشل. لقد وجدت فقط 10000 طريقة لن تنجح.", author: "توماس إديسون" },
        { quote: "إذا كانت أفعالك تلهم الآخرين ليحلموا أكثر، ويتعلموا أكثر، ويفعلوا أكثر، ويصبحوا أكثر، فأنت قائد.", author: "جون كوينسي آدامز" },
        { quote: "الفرق بين العادي والاستثنائي هو تلك اللمسة الصغيرة الإضافية.", author: "جيمي جونسون" },
        { quote: "رحلة الألف ميل تبدأ بخطوة واحدة.", author: "لاو تسو" },
        { quote: "إما أن تكتب شيئًا يستحق القراءة أو تفعل شيئًا يستحق الكتابة.", author: "بنجامين فرانكلين" },
        { quote: "لا يمكن تطوير الشخصية في السهولة والهدوء. فقط من خلال تجربة المحاولة والمعاناة يمكن تقوية الروح وإلهام الطموح وتحقيق النجاح.", author: "هيلين كيلر" },
        { quote: "كل أحلامنا يمكن أن تتحقق، إذا كانت لدينا الشجاعة لمتابعتها.", author: "والت ديزني" },
        { quote: "الشيء الوحيد الذي يقف بينك وبين حلمك هو الرغبة في المحاولة والاعتقاد بأنه ممكن بالفعل.", author: "جويل براون" },
        { quote: "لا تدع الأمس يستهلك الكثير من اليوم.", author: "ويل روجرز" },
        { quote: "سواء كنت تعتقد أنك تستطيع أو لا تستطيع، فأنت على حق.", author: "هنري فورد" },
        { quote: "الإبداع هو الذكاء وهو يمرح.", author: "ألبرت أينشتاين" },
        { quote: "المستقبل ملك لأولئك الذين يؤمنون بجمال أحلامهم.", author: "إليانور روزفلت" },
        { quote: "لا تحسب الأيام، بل اجعل الأيام ذات قيمة.", author: "محمد علي كلاي" },
        { quote: "القوة لا تأتي من القدرة الجسدية. إنها تأتي من إرادة لا تقهر.", author: "غاندي" },
        { quote: "الأوقات الصعبة لا تدوم أبدًا، لكن الأشخاص الأقوياء يدومون.", author: "روبرت شولر" },
        { quote: "لا يهم مدى بطئك طالما أنك لا تتوقف.", author: "كونفوشيوس" },
        { quote: "لكي تنجح، يجب أن تكون رغبتك في النجاح أكبر من خوفك من الفشل.", author: "بيل كوسبي" },
        { quote: "عندما يبدو كل شيء وكأنه يسير ضدك، تذكر أن الطائرة تقلع عكس اتجاه الريح، وليس معها.", author: "هنري فورد" },
        { quote: "العبقرية هي 1% إلهام و 99% عرق.", author: "توماس إديسون" },
        { quote: "الحياة 10% ما يحدث لنا و 90% كيف نرد عليه.", author: "تشارلز سويندول" },
        { quote: "اذهب بثقة في اتجاه أحلامك. عش الحياة التي تخيلتها.", author: "هنري ديفيد ثورو" },
        { quote: "بعد عشرين عامًا من الآن، ستكون أكثر خيبة أمل من الأشياء التي لم تفعلها من تلك التي فعلتها.", author: "مارك توين" },
        { quote: "حدد أهدافك عالياً، ولا تتوقف حتى تصل إلى هناك.", author: "بو جاكسون" },
        { quote: "آمن بنفسك وبكل ما تملك. اعلم أن هناك شيئًا بداخلك أعظم من أي عقبة.", author: "كريستيان د. لارسون" },
        { quote: "التفاؤل هو الإيمان الذي يؤدي إلى الإنجاز. لا شيء يمكن أن يتم بدون أمل وثقة.", author: "هيلين كيلر" },
        { quote: "ابدأ بفعل ما هو ضروري، ثم ما هو ممكن، وفجأة ستجد نفسك تفعل المستحيل.", author: "فرنسيس الأسيزي" },
        { quote: "السر في المضي قدمًا هو البدء.", author: "مارك توين" },
        { quote: "الجودة ليست فعلًا، إنها عادة.", author: "أرسطو" },
        { quote: "إذا كان عقلك يستطيع تصورها، وإذا كان قلبك يستطيع الإيمان بها، فبإمكانك تحقيقها.", author: "جيسي جاكسون" },
        { quote: "لا يوجد مصعد للنجاح، عليك أن تأخذ السلالم.", author: "زيج زيجلار" },
        { quote: "نحن نتاج عاداتنا. إذن، التميز ليس فعلًا، بل عادة.", author: "أرسطو" },
        { quote: "إذا لم تكن على استعداد للمخاطرة بما هو غير عادي، فسيتعين عليك أن ترضى بما هو عادي.", author: "جيم رون" },
        { quote: "الثقة بالنفس هي أول سر للنجاح.", author: "رالف والدو إمرسون" },
        { quote: "الألم مؤقت. قد يستمر لدقيقة، أو ساعة، أو يوم، أو سنة، لكنه في النهاية سيزول وسيحل محله شيء آخر. أما إذا استسلمت، فسيدوم إلى الأبد.", author: "لانس أرمسترونغ" },
        { quote: "النجاح هو مجموع الجهود الصغيرة التي تتكرر يومًا بعد يوم.", author: "روبرت كولير" },
        { quote: "أعظم متعة في الحياة هي فعل ما يقول الناس إنك لا تستطيع فعله.", author: "والتر باجهوت" },
        { quote: "لتكن أفعالك هي الضوضاء الوحيدة.", author: "مجهول" }
    ],
    en: [
        { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
        { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
        { quote: "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking.", author: "Steve Jobs" },
        { quote: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt" },
        { quote: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", author: "Oprah Winfrey" },
        { quote: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", author: "James Cameron" },
        { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
        { quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
        { quote: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
        { quote: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead" },
        { quote: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
        { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
        { quote: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
        { quote: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", author: "Helen Keller" },
        { quote: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
        { quote: "Whoever is happy will make others happy too.", author: "Anne Frank" },
        { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
        { quote: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou" },
        { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
        { quote: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
        { quote: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
        { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
        { quote: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas A. Edison" },
        { quote: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss" },
        { quote: "Success is not final; failure is not fatal: It is the courage to continue that counts.", author: "Winston S. Churchill" },
        { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
        { quote: "In this life we cannot do great things. We can only do small things with great love.", author: "Mother Teresa" },
        { quote: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein" },
        { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
        { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
        { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
        { quote: "Live in the sunshine, swim the sea, drink the wild air.", author: "Ralph Waldo Emerson" },
        { quote: "Go confidently in the direction of your dreams! Live the life you've imagined.", author: "Henry David Thoreau" },
        { quote: "The greatest pleasure in life is doing what people say you cannot do.", author: "Walter Bagehot" },
        { quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
        { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
        { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
        { quote: "It is not how much we have, but how much we enjoy, that makes happiness.", author: "Charles Spurgeon" },
        { quote: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller Jr." },
        { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
        { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
        { quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
        { quote: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
        { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
        { quote: "I never dreamed about success. I worked for it.", author: "Estée Lauder" },
        { quote: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
        { quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
        { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
        { quote: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
        { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" }
    ],
    fr: [
        { quote: "La plus grande gloire n'est pas de ne jamais tomber, mais de se relever à chaque chute.", author: "Nelson Mandela" },
        { quote: "La seule façon de faire un excellent travail est d'aimer ce que vous faites.", author: "Steve Jobs" },
        { quote: "Soyez le changement que vous voulez voir dans le monde.", author: "Gandhi" },
        { quote: "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.", author: "Winston Churchill" },
        { quote: "N'attendez pas l'opportunité. Créez-la.", author: "George Bernard Shaw" },
        { quote: "L'esprit est tout. Ce que vous pensez, vous le devenez.", author: "Bouddha" },
        { quote: "Commencez où vous êtes. Utilisez ce que vous avez. Faites ce que vous pouvez.", author: "Arthur Ashe" },
        { quote: "Les défis sont ce qui rend la vie intéressante et les surmonter est ce qui lui donne un sens.", author: "Joshua J. Marine" },
        { quote: "Une personne qui n'a jamais commis d'erreur n'a jamais rien essayé de nouveau.", author: "Albert Einstein" },
        { quote: "Le meilleur moment pour planter un arbre était il y a 20 ans. Le deuxième meilleur moment est maintenant.", author: "Proverbe chinois" }
    ],
    tr: [
        { quote: "Yaşamdaki en büyük zafer hiç düşmemek değil, her düştüğünde yeniden ayağa kalkmaktır.", author: "Nelson Mandela" },
        { quote: "Harika bir iş yapmanın tek yolu, yaptığınız işi sevmektir.", author: "Steve Jobs" },
        { quote: "Dünyada görmek istediğin değişim kendin ol.", author: "Gandhi" },
        { quote: "Başarı nihai değildir, başarısızlık ölümcül değildir: Önemli olan devam etme cesaretidir.", author: "Winston Churchill" },
        { quote: "Fırsatı beklemeyin. Yaratın.", author: "George Bernard Shaw" },
        { quote: "Akıl her şeydir. Ne düşünürsen, o olursun.", author: "Buda" },
        { quote: "Olduğun yerden başla. Sahip olduklarını kullan. Yapabildiğini yap.", author: "Arthur Ashe" },
        { quote: "Hayatı ilginç kılan zorluklardır ve onların üstesinden gelmek hayata anlam katar.", author: "Joshua J. Marine" },
        { quote: "Hiç hata yapmamış bir insan, hiç yeni bir şey denememiştir.", author: "Albert Einstein" },
        { quote: "Bir ağaç dikmek için en iyi zaman 20 yıl önceydi. İkinci en iyi zaman ise şimdi.", author: "Çin Atasözü" }
    ],
    id: [
        { quote: "Kemuliaan terbesar dalam hidup bukan terletak pada tidak pernah jatuh, tetapi pada bangkit setiap kali kita jatuh.", author: "Nelson Mandela" },
        { quote: "Satu-satunya cara untuk melakukan pekerjaan hebat adalah dengan mencintai apa yang Anda lakukan.", author: "Steve Jobs" },
        { quote: "Jadilah perubahan yang ingin kamu lihat di dunia.", author: "Gandhi" },
        { quote: "Kesuksesan bukanlah akhir, kegagalan bukanlah hal yang fatal: Keberanian untuk melanjutkanlah yang terpenting.", author: "Winston Churchill" },
        { quote: "Jangan menunggu kesempatan. Ciptakanlah.", author: "George Bernard Shaw" },
        { quote: "Pikiran adalah segalanya. Apa yang Anda pikirkan, itulah jadinya Anda.", author: "Buddha" },
        { quote: "Mulailah dari tempat Anda berada. Gunakan apa yang Anda miliki. Lakukan apa yang Anda bisa.", author: "Arthur Ashe" },
        { quote: "Tantangan adalah apa yang membuat hidup menarik, dan mengatasinya adalah apa yang membuat hidup berarti.", author: "Joshua J. Marine" },
        { quote: "Seseorang yang tidak pernah membuat kesalahan tidak pernah mencoba sesuatu yang baru.", author: "Albert Einstein" },
        { quote: "Waktu terbaik untuk menanam pohon adalah 20 tahun yang lalu. Waktu terbaik kedua adalah sekarang.", author: "Pepatah Cina" }
    ]
};

    